packages:
  - "packages/*"
  - "apps/*"
  - "examples"
  - "examples/*"

onlyBuiltDependencies:
  - esbuild
  - "@modelcontextprotocol/sdk"
allowBuilds:
  esbuild: true
  "@modelcontextprotocol/sdk": true
